# Set machine below and adjust paths if needed.
machine: local   # canfar | narval | local

logging:
  name: download_test
  level: INFO

runtime:
  n_download_threads: 12
  bands: ["whigs-g", "cfis_lsb-r", "ps-i"]                         # "cfis-u", "whigs-g", "cfis_lsb-r", "ps-i", "wishes-z"
  resume: false

tiles:
  update_tiles: false                                              # set to true to update tile list from the VOS vault
  show_tile_statistics: true
  band_constraint: 1                                               # min bands for a tile to qualify for download

inputs:
  # Choose the input source
  source: "dataframe"                                            # all_available | tiles | coordinates | dataframe
  # Pairs: [[x1, y1], [x2, y2], ...]
  tiles:
    - [217, 292]
    - [234, 295]

  # Pairs: [[ra1, dec1], [ra2, dec2], ...]
  coordinates:
    - [227.3042, 52.5285]
    - [231.4445, 52.4447]

  dataframe:
    path: "/home/nick/astro/unionsdata/tables/M101_lsb.csv"        # CSV with RA/Dec/ID columns
    columns:
      ra: "ra"                                                     # Right Ascension column name
      dec: "dec"                                                   # Declination column name
      id: "ID"                                                     # ID column name

paths_common:
  # These are joined under root_dir_main
  tile_info_dirname: "tile_info"
  logs_dirname:      "logs"

paths_by_machine:
  canfar:
    root_dir_main: "/arc/home/heestersnick/unionsdata"
    root_dir_data: "/arc/projects/unions"

  narval:
    root_dir_main: "/home/heesters/projects/def-sfabbro/heesters/github/TileSlicer"
    root_dir_data: "/home/heesters/projects/def-sfabbro/heesters/data/unions"

  local:
    root_dir_main: "/home/nick/astro/unionsdata"
    root_dir_data: "/home/nick/astro/unionsdata/data"

bands:
  cfis-u:
    name: "CFIS"
    band: "u"
    vos: "vos:cfis/tiles_DR5"
    suffix: ".u.fits"
    delimiter: "."
    fits_ext: 0
    zfill: 3
    zp: 30.0

  whigs-g:
    name: "calexp-CFIS"
    band: "g"
    vos: "vos:cfis/whigs/stack_images_CFIS_scheme"
    suffix: ".fits"
    delimiter: "_"
    fits_ext: 1
    zfill: 0
    zp: 27.0

  cfis_lsb-r:
    name: "CFIS_LSB"
    band: "r"
    vos: "vos:cfis/tiles_LSB_DR5"
    suffix: ".r.fits"
    delimiter: "."
    fits_ext: 0
    zfill: 3
    zp: 30.0

  ps-i:
    name: "PSS.DR4"
    band: "i"
    vos: "vos:cfis/panstarrs/DR4/resamp"
    suffix: ".i.fits"
    delimiter: "."
    fits_ext: 0
    zfill: 3
    zp: 30.0

  wishes-z:
    name: "WISHES"
    band: "z"
    vos: "vos:cfis/wishes_1/coadd"
    suffix: ".z.fits"
    delimiter: "."
    fits_ext: 1
    zfill: 0
    zp: 27.0

  ps-z:
    name: "PSS.DR4"
    band: "ps-z"
    vos: "vos:cfis/panstarrs/DR4/resamp"
    suffix: ".z.fits"
    delimiter: "."
    fits_ext: 0
    zfill: 3
    zp: 30.0
